### PR TITLE
Add additional backslash to escapedPrompt

### PR DESCRIPTION
**Pull request by rahmaniaam**
## Problem
Chat prompts with a sequence of multiple backslashes will result in backslashes to be gone in the prompt card

Input example:
```
Make a regex that get '\\(' occurrences on string

Make a regex that get \\( occurrences on string

Make a regex that get\\( occurrences on string

Make a regex that get \\(occurrences on string

Make a regex that get '\\\(' occurrences on string

Make a regex that get '\\' occurrences on string

Make a regex that get \\ occurrences on string

Make a regex that get \' occurrences on string

Make a regex that get '\ occurrences on string
```

Result:
Screenshot 2024-12-24 at 15 37 00

## Solution
Add regex logic in the escaped prompt to add an additional backslash on sequences of backslashes

Result:
Screenshot 2024-12-24 at 15 35 24

## Tests
- [ ] I have tested this change on VSCode
- [ ] I have tested this change on JetBrains

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Jurredr** [comment]
Nice fix with the regex, seems to work as expected. Just wondering; do we know what exactly is the root cause of this? Is there not something we can do to prevent it in the first place, rather than patching it up with a replacement?

**Comment by rahmaniaam** [comment]
> Just wondering; do we know what exactly is the root cause of this? Is there not something we can do to prevent it in the first place, rather than patching it up with a replacement?

From what I can tell, it doesn't seem that the `escapeHTML` function successfully interpret the backslashes resulting in the card to render incorrectly, we may need to use a different library

**Comment by rahmaniaam** [comment]
This needs more work, playing around with escaping backticks is still messing it up:

Input
```
Make a regex that get `\``\\(``` occurrences on string
```
or
```
Make a regex that get ```\\(``\` occurrences on string
```
Output
```
Make a regex that get ```\(``` occurrences on string
```

**Comment by dogusata** [comment]
The current behavior works as expected for a markdown input field. It is also the exact same behavior for the Github or any other markdown supported entry field in general.

**Pull request closed without merging**
